import test from 'node:test';
import assert from 'node:assert/strict';
import {loadTool,vue,window,waitFor} from './helpers/tool-dom.mjs';
import {createRequire} from 'node:module';
globalThis.history=window.history;
const require=createRequire(import.meta.url),{createRouter,createMemoryHistory}=require('vue-router');
const Login=(await import(await loadTool('src/views/Login.vue'))).default;
async function mount(path,fetcher){const previous=globalThis.fetch;globalThis.fetch=fetcher;const router=createRouter({history:createMemoryHistory(),routes:[{path:'/',component:{template:'<p>square</p>'}},{path:'/login',component:Login},{path:'/studio',component:{template:'<p>studio</p>'}},{path:'/tools',component:{template:'<p>tools</p>'}}]});await router.push(path);await router.isReady();const host=document.createElement('div');document.body.append(host);const app=vue.createApp({render:()=>vue.h(require('vue-router').RouterView)});app.use(router);app.mount(host);return {host,router,close(){app.unmount();host.remove();globalThis.fetch=previous}}}
const response=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json'}});
function setInput(input,value){input.value=value;input.dispatchEvent(new window.Event('input',{bubbles:true}))}
test('mounted login disabled state never exposes a usable registration or credential form',async()=>{const m=await mount('/login',async()=>response({user:null,identityEnabled:false}));try{await waitFor(()=>m.host.textContent.includes('登录暂未开放'));assert.equal(m.host.querySelector('form'),null);assert.equal(m.host.querySelector('input[type=password]'),null)}finally{m.close()}});
test('mounted email login attaches CSRF, blocks double submit, reports failure then returns safely after retry',async()=>{let release,attempts=0;const calls=[];const fetcher=async(url,options={})=>{calls.push({url,options});if(url==='/api/me')return response({user:null,identityEnabled:true});if(url==='/api/auth/session')return response({user:null,csrfToken:'c'.repeat(43),registrationOpen:true});if(url==='/api/auth/login'){attempts++;if(attempts===1)return new Promise(r=>{release=()=>r(response({error:'邮箱或密码不正确。'},401))});return response({user:'fixture-id',csrfToken:'d'.repeat(43)})}throw Error(url)};
 const m=await mount('/login?returnTo=%2Ftools',fetcher);try{await waitFor(()=>m.host.querySelector('form'));setInput(m.host.querySelector('input[type=email]'),'fixture@example.com');setInput(m.host.querySelector('input[type=password]'),'isolated fixture long password');const submit=()=>m.host.querySelector('form').dispatchEvent(new window.Event('submit',{bubbles:true,cancelable:true}));submit();await waitFor(()=>!!release);submit();await vue.nextTick();assert.equal(attempts,1);release();await waitFor(()=>m.host.querySelector('[role=alert]'));assert.match(m.host.textContent,/邮箱或密码不正确/);submit();await waitFor(()=>m.router.currentRoute.value.path==='/tools');const call=calls.find(c=>c.url==='/api/auth/login');assert.equal(call.options.headers.get('X-CSRF-Token'),'c'.repeat(43));assert.equal(call.options.credentials,'same-origin');assert.equal(JSON.parse(call.options.body).email,'fixture@example.com');assert.equal(m.host.querySelector('input[type=password]'),null)}finally{m.close()}
});
test('mounted email verification removes fragment, checks confirmation and consumes token only on explicit submit',async()=>{const token='v'.repeat(43),calls=[];const m=await mount('/login#verify='+token,async(url,options={})=>{calls.push({url,options});if(url==='/api/me')return response({user:null,identityEnabled:true});if(url==='/api/auth/session')return response({user:null,csrfToken:'c'.repeat(43),registrationOpen:true});if(url==='/api/auth/verify')return response({user:'fixture',csrfToken:'d'.repeat(43)});throw Error(url)});try{await waitFor(()=>m.host.querySelectorAll('input[type=password]').length===2);assert.equal(m.router.currentRoute.value.hash,'');assert.equal(calls.some(c=>c.url==='/api/auth/verify'),false);const inputs=m.host.querySelectorAll('input[type=password]');setInput(inputs[0],'isolated fixture long password');setInput(inputs[1],'different fixture password');m.host.querySelector('form').dispatchEvent(new window.Event('submit',{bubbles:true,cancelable:true}));await waitFor(()=>m.host.textContent.includes('两次密码不一致'));assert.equal(calls.some(c=>c.url==='/api/auth/verify'),false);setInput(inputs[1],'isolated fixture long password');m.host.querySelector('form').dispatchEvent(new window.Event('submit',{bubbles:true,cancelable:true}));await waitFor(()=>m.router.currentRoute.value.path==='/studio');assert.equal(JSON.parse(calls.find(c=>c.url==='/api/auth/verify').options.body).token,token)}finally{m.close()}});
