import test from 'node:test'
import assert from 'node:assert/strict'
import {readFile} from 'node:fs/promises'
import {createRequire} from 'node:module'
import {pathToFileURL} from 'node:url'
import ts from 'typescript'
import {createCanvas,loadImage} from '@napi-rs/canvas'
import sharp from 'sharp'
const require=createRequire(import.meta.url)
const compile=async(path,replacements=[])=>{let source=await readFile(new URL(path,import.meta.url),'utf8');for(const [a,b]of replacements)source=source.replace(a,b);return 'data:text/javascript;base64,'+Buffer.from(ts.transpileModule(source,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ES2022}}).outputText).toString('base64')}
const core=await compile('../src/tools/core/document.ts'),collage=await compile('../src/tools/core/collage.ts'),assetsURL=await compile('../src/tools/engine/assets.ts',[["'../core/document'",JSON.stringify(core)],["'exifr'",JSON.stringify(pathToFileURL(require.resolve('exifr')).href)]]),renderURL=await compile('../src/tools/engine/render.ts',[["'../core/document'",JSON.stringify(core)],["'./assets'",JSON.stringify(assetsURL)]]),collageRender=await compile('../src/tools/engine/collage-render.ts',[["'../core/collage'",JSON.stringify(collage)],["'../core/document'",JSON.stringify(core)],["'./assets'",JSON.stringify(assetsURL)]]),pipeline=await compile('../src/tools/engine/pipeline.ts',[["'./render'",JSON.stringify(renderURL)],["'./collage-render'",JSON.stringify(collageRender)]])
const {collageDefaults,cells,imageRect,moveAsset,replaceAsset}=await import(collage),{Assets,preflight}=await import(assetsURL),{renderCollage}=await import(collageRender),{render,encode}=await import(renderURL),{defaults,History}=await import(core),{SerialGate}=await import(pipeline)
let open=0,peak=0,maxPixels=0,decoded=0
// Uses real Sharp orientation + Skia pixels to simulate from-image, not a browser compatibility test.
globalThis.createImageBitmap=async(source,opts={})=>{assert.equal(opts.imageOrientation,'from-image');const buffer=Buffer.from(await source.arrayBuffer());const resized=await sharp(buffer).rotate().resize(opts.resizeWidth,opts.resizeHeight,{fit:'fill'}).png().toBuffer();const image=await loadImage(resized),c=createCanvas(image.width,image.height);c.getContext('2d').drawImage(image,0,0);open++;decoded++;peak=Math.max(peak,open);maxPixels=Math.max(maxPixels,c.width*c.height);let closed=false;c.close=()=>{if(!closed){closed=true;open--}};return c}
globalThis.document={createElement:()=>createCanvas(1,1),fonts:{ready:Promise.resolve(),load:async()=>[]}}
const file=async(name,color,width=1200,height=800)=>new File([await sharp({create:{width,height,channels:3,background:color}}).jpeg().toBuffer()],name,{type:'image/jpeg'})
test('reorder, replacement, mode changes and undo preserve independent per-photo crop',()=>{const a={...collageDefaults(),assetIds:['a','b','c'],placements:{a:{x:20,y:80,fit:'cover'},b:{x:50,y:50,fit:'contain'}}};const moved=moveAsset(a,'a',1);assert.deepEqual(moved.assetIds,['b','a','c']);assert.deepEqual(moved.placements,a.placements);const replaced=replaceAsset(moved,'a','new');assert.deepEqual(replaced.assetIds,['b','new','c']);assert.deepEqual(replaced.placements.new,a.placements.a);const history=new History(a);history.commit(replaced);assert.deepEqual(history.undo(),a);for(const mode of ['grid','row','column']){const d={...replaced,mode};assert.equal(cells(d).length,3);assert.deepEqual(d.placements.new,a.placements.a)}})
test('cover focus endpoints crop independently, contain preserves whole image, invalid spacing rejects',()=>{const cell={id:'a',x:10,y:20,width:100,height:100};assert.deepEqual(imageRect({width:200,height:100},cell,{x:0,y:50,fit:'cover'}),{x:10,y:20,width:200,height:100});assert.equal(imageRect({width:200,height:100},cell,{x:100,y:50,fit:'cover'}).x,-90);assert.deepEqual(imageRect({width:200,height:100},cell,{x:50,y:50,fit:'contain'}),{x:10,y:45,width:100,height:50});assert.throws(()=>cells({...collageDefaults(),width:64,height:64,assetIds:['a','b'],padding:40}),/没有可用面积/)})
test('12-image actual render is serial, exported PNG dimensions match and cancellation frees active bitmap',async()=>{const repo=new Assets(),d={...collageDefaults(),width:720,height:480,columns:4,format:'image/png'};for(let i=0;i<12;i++){const a=await repo.add(await file('photo-'+i+'.jpg',{r:i*20,g:50,b:90}));d.assetIds.push(a.id)}const statuses=[];const c=createCanvas(1,1);await renderCollage(d,repo.items,c,false,()=>{},s=>statuses.push(s));const blob=await encode(c,d),meta=await sharp(Buffer.from(await blob.arrayBuffer())).metadata();assert.equal(meta.width,720);assert.equal(meta.height,480);assert.ok(statuses.includes('已绘制 12/12'));assert.equal(open,0);assert.equal(peak,1);const before=decoded;await assert.rejects(renderCollage(d,repo.items,createCanvas(1,1),false,()=>{if(decoded>before)throw new DOMException('cancel','AbortError')},()=>{}),{name:'AbortError'});assert.equal(open,0);repo.dispose();assert.equal(repo.items.size,0)})
test('original crop focus changes rendered pixels; preview equals full render at same output size',async()=>{const bands=await sharp({create:{width:200,height:100,channels:3,background:'#ff0000'}}).composite([{input:await sharp({create:{width:100,height:100,channels:3,background:'#0000ff'}}).png().toBuffer(),left:100,top:0}]).png().toBuffer();const repo=new Assets(),a=await repo.add(new File([bands],'bands.png',{type:'image/png'})),d={...collageDefaults(),width:100,height:100,columns:1,gap:0,padding:0,assetIds:[a.id],placements:{[a.id]:{x:0,y:50,fit:'cover'}},format:'image/png'};const left=createCanvas(1,1);await renderCollage(d,repo.items,left,false,()=>{},()=>{});assert.ok(left.getContext('2d').getImageData(50,50,1,1).data[0]>240);d.placements[a.id].x=100;const right=createCanvas(1,1),preview=createCanvas(1,1);await renderCollage(d,repo.items,right,false,()=>{},()=>{});await renderCollage(d,repo.items,preview,true,()=>{},()=>{});assert.ok(right.getContext('2d').getImageData(50,50,1,1).data[2]>240);assert.deepEqual(right.getContext('2d').getImageData(0,0,100,100).data,preview.getContext('2d').getImageData(0,0,100,100).data);repo.dispose()})
test('EXIF orientation 1–8 is normalized exactly once in watermark and original bytes stay intact',async()=>{const colors=['#ff0000','#00ff00','#0000ff','#ffff00'];const quadrants=await Promise.all(colors.map(background=>sharp({create:{width:32,height:20,channels:3,background}}).png().toBuffer()));const base=await sharp({create:{width:64,height:40,channels:3,background:'#000'}}).composite(quadrants.map((input,i)=>({input,left:(i%2)*32,top:Math.floor(i/2)*20}))).jpeg({quality:100}).toBuffer();const expected=[[0,1,2,3],[1,0,3,2],[3,2,1,0],[2,3,0,1],[0,2,1,3],[2,0,3,1],[3,1,2,0],[1,3,0,2]],rgb=[[255,0,0],[0,255,0],[0,0,255],[255,255,0]];for(let orientation=1;orientation<=8;orientation++){const bytes=await sharp(base).withMetadata({orientation}).jpeg({quality:100}).toBuffer(),f=new File([bytes],'orientation-'+orientation+'.jpg',{type:'image/jpeg'}),repo=new Assets(),a=await repo.add(f),canvas=createCanvas(1,1);assert.equal(a.width,orientation>=5?40:64);assert.equal(a.height,orientation>=5?64:40);await render({...defaults(),border:0,format:'image/png'},a,canvas,false,()=>{},()=>{});for(let i=0;i<4;i++){const pixel=canvas.getContext('2d').getImageData(Math.floor(canvas.width*((i%2)?.75:.25)),Math.floor(canvas.height*(i<2?.25:.75)),1,1).data,want=rgb[expected[orientation-1][i]];for(let c=0;c<3;c++)assert.ok(Math.abs(pixel[c]-want[c])<35,`orientation ${orientation} quadrant ${i}`)}assert.deepEqual(Buffer.from(await f.arrayBuffer()),bytes);repo.dispose();assert.equal(open,0)}})
test('large 40MP source uses 320px thumbnail, 1600px preview and rejects >40MP before decode',async()=>{const repo=new Assets(),f=await file('large.jpg','#647d86',8000,5000),a=await repo.add(f);assert.equal(a.width,8000);assert.equal(a.height,5000);const c=createCanvas(1,1);await render({...defaults(),border:0},a,c,true,()=>{},()=>{});assert.equal(c.width,1600);assert.equal(c.height,1000);assert.equal(open,0);const bytes=new Uint8Array(24);bytes.set([137,80,78,71,13,10,26,10]);new DataView(bytes.buffer).setUint32(16,8001);new DataView(bytes.buffer).setUint32(20,5000);const before=decoded;await assert.rejects(preflight(new File([bytes],'too-large.png',{type:'image/png'})),/4000/);assert.equal(decoded,before);repo.dispose()})
test('serial gate survives errors, does not overlap jobs, and repeated import/prune leaves zero live bitmaps',async()=>{const gate=new SerialGate();let active=0,max=0;await Promise.all([1,2,3].map(i=>gate.run(async()=>{active++;max=Math.max(max,active);await new Promise(r=>setTimeout(r,2));active--;if(i===2)throw Error('expected')}).catch(()=>{})));assert.equal(max,1);const repo=new Assets(),f=await file('repeat.jpg','#123456',320,240);for(let i=0;i<20;i++){await repo.add(f);repo.prune(new Set());assert.equal(repo.items.size,0);assert.equal(open,0)}repo.dispose();assert.equal(open,0)})

test('collage transparent PNG leaves gutters transparent and WebP export has its true MIME and dimensions',async()=>{const repo=new Assets(),a=await repo.add(await file('alpha.jpg','#ff0000',120,80)),d={...collageDefaults(),assetIds:[a.id],width:200,height:200,columns:1,transparent:true,format:'image/png'};const c=createCanvas(1,1);await renderCollage(d,repo.items,c,false,()=>{},()=>{});assert.equal(c.getContext('2d').getImageData(0,0,1,1).data[3],0);d.format='image/jpeg';await renderCollage(d,repo.items,c,false,()=>{},()=>{});assert.equal(c.getContext('2d').getImageData(0,0,1,1).data[3],255);d.format='image/webp';await renderCollage(d,repo.items,c,false,()=>{},()=>{});const blob=await encode(c,d),meta=await sharp(Buffer.from(await blob.arrayBuffer())).metadata();assert.equal(blob.type,'image/webp');assert.equal(meta.format,'webp');assert.equal(meta.width,200);assert.equal(meta.height,200);repo.dispose()})
