<script setup>
import { computed, ref, onMounted } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { readSession, safeReturnTo, loginReturnTarget } from '../auth/session.mjs'
const route=useRoute(),router=useRouter(),busy=ref(true),error=ref(''),returnTo=computed(()=>safeReturnTo(route.query.returnTo))
async function checkSession(){busy.value=true;error.value='';try{const session=await readSession();const target=loginReturnTarget(session,route.query.returnTo);if(target)await router.replace(target)}catch(e){error.value=e.message}finally{busy.value=false}}
onMounted(checkSession)
</script>
<template>
 <section class="markr-page login-page">
  <div class="login-intro"><span class="eyebrow">YOUR SPACE ON MARKR</span><h1>把作品整理成<br>属于你的空间。</h1><p>保存草稿、发布作品、整理作品集，分享你的摄影视角。</p><div class="login-rule"></div><router-link to="/tools">只想处理照片？打开工具箱 →</router-link></div>
  <div class="login-panel"><span class="eyebrow">ACCOUNT</span><h2>登录 Markr</h2><p v-if="busy" role="status" class="state-message">正在检查登录状态……</p><div v-else-if="error" role="alert" class="state-message state-error"><p>{{error}}</p><button class="btn btn-secondary" @click="checkSession">重试</button></div><div v-else class="state-message"><span class="status-label">登录暂未开放</span><p>账户服务正在准备中，当前不能登录或注册。工具箱无需账号即可使用。</p></div><div class="login-fields" aria-label="尚未开放的登录表单"><label>账号<input disabled placeholder="账户服务启用后可填写" autocomplete="off"></label><label>密码<input disabled type="password" placeholder="暂不可用" autocomplete="off"></label><button class="btn btn-primary" disabled>登录暂未开放</button></div><p class="return-note">登录成功后将返回{{returnTo.startsWith('/studio')?'我的工作台':'原来的页面'}}。</p><router-link class="login-back" to="/">返回广场</router-link></div>
 </section>
</template>
<style scoped>
.login-page{min-height:calc(100vh - 180px);display:grid;grid-template-columns:1fr 420px;align-items:center;gap:clamp(40px,7vw,120px);padding-top:72px;padding-bottom:72px}.login-intro h1{font-size:clamp(32px,4.5vw,58px);line-height:1.2;font-weight:450;letter-spacing:-.035em;margin:24px 0}.login-intro>p{color:var(--markr-muted);max-width:400px;line-height:1.9}.login-rule{height:1px;max-width:400px;background:var(--markr-line);margin:32px 0}.login-intro a{font-size:13px;color:var(--markr-accent);text-decoration:none}.login-panel{padding:32px;border:1px solid var(--markr-line);background:var(--markr-surface);border-radius:var(--markr-radius)}.login-panel h2{font-size:26px;font-weight:500;margin:14px 0 24px}.state-message{font-size:13px;line-height:1.8;padding:16px;background:var(--markr-surface-raised);border:1px solid var(--markr-line);border-radius:var(--markr-radius-small);color:var(--markr-muted);margin-bottom:24px}.status-label{display:block;color:var(--markr-text);margin-bottom:6px}.state-error{border-color:var(--markr-error);color:var(--markr-error)}.state-message .btn{margin-top:12px}.login-fields label{display:block;font-size:13px;margin:16px 0;color:var(--markr-muted)}.login-fields input{display:block;width:100%;padding:12px;border:1px solid var(--markr-line);border-radius:var(--markr-radius-small);background:var(--markr-bg);margin-top:8px;color:var(--markr-muted)}.login-fields .btn{width:100%;margin-top:8px}.return-note{font-size:12px;color:var(--markr-muted);margin-top:16px}.login-back{display:inline-block;margin-top:24px;color:var(--markr-text);font-size:13px;text-decoration:none}@media(max-width:850px){.login-page{grid-template-columns:1fr;max-width:620px;padding-top:40px;gap:32px}.login-intro h1{font-size:36px}.login-rule{margin:20px 0}.login-panel{padding:24px}}
</style>
