<script setup>
const tools=[{path:'/frame-watermark',number:'01',title:'边框水印',description:'为照片添加留白、边框与拍摄参数。',detail:'单张成片 · 边框与签名',shape:'frame'},{path:'/image-collage',number:'02',title:'图片拼图',description:'组合多个画面，让影像形成完整叙事。',detail:'多张成片 · 自由组合',shape:'collage'}]
</script>
<template>
 <section class="markr-page toolbox-page">
  <div class="page-intro"><span class="eyebrow">YOUR CREATIVE DESK</span><h1>工具箱</h1><p>让照片拥有自己的表达。处理始终在你的浏览器中完成。</p></div>
  <div class="tool-grid"><router-link v-for="tool in tools" :key="tool.path" :to="tool.path" class="tool-tile"><div class="tool-illustration" :class="tool.shape" aria-hidden="true"><span></span><span></span><span></span></div><div class="tool-tile-body"><span class="eyebrow">{{tool.number}} / {{tool.detail}}</span><h2>{{tool.title}}<span aria-hidden="true">↗</span></h2><p>{{tool.description}}</p><span class="tool-entry">开始创作 →</span></div></router-link></div>
  <div class="local-note"><span class="status-dot" aria-hidden="true"></span><p>无需登录 · 不自动上传 · 原文件由你保管</p><small>完成后可以导出结果。若要分享，需在工作台主动选择上传。</small></div>
 </section>
</template>
<style scoped>
.toolbox-page{padding-top:64px;padding-bottom:72px}.tool-grid{display:grid;grid-template-columns:1fr 1fr;gap:24px;margin-top:48px}.tool-tile{display:block;text-decoration:none;color:inherit;border:1px solid var(--markr-line);border-radius:var(--markr-radius);overflow:hidden;background:var(--markr-surface);transition:border-color .18s}.tool-tile:hover{border-color:var(--markr-muted)}.tool-illustration{height:260px;background:#101214;display:flex;align-items:center;justify-content:center;gap:10px;border-bottom:1px solid var(--markr-line)}.frame span:first-child{width:52%;height:65%;border:16px solid #d9d9d2;background:linear-gradient(150deg,#4c575b 50%,#232e31 50%);box-shadow:0 12px 30px #0004}.frame span:not(:first-child){display:none}.collage span{height:54%;width:24%;background:#303b3c}.collage span:first-child{background:linear-gradient(135deg,#52615c 45%,#26332d 45%);transform:translateY(-14px)}.collage span:nth-child(2){background:linear-gradient(150deg,#615b50 60%,#383a33 60%)}.collage span:last-child{background:linear-gradient(135deg,#484f5a 35%,#252c37 35%);transform:translateY(14px)}.tool-tile-body{padding:28px}.tool-tile h2{display:flex;justify-content:space-between;font-weight:500;font-size:26px;margin:16px 0 8px}.tool-tile h2 span{color:var(--markr-muted);font-size:20px}.tool-tile p{color:var(--markr-muted);font-size:14px}.tool-entry{display:block;margin-top:28px;color:var(--markr-accent);font-size:13px}.local-note{display:grid;grid-template-columns:8px 1fr;column-gap:12px;align-items:center;margin-top:36px;color:var(--markr-muted)}.local-note p{font-size:13px}.local-note small{grid-column:2;font-size:12px;margin-top:6px}.status-dot{height:6px;width:6px;border-radius:50%;background:var(--markr-accent)}@media(max-width:700px){.tool-grid{grid-template-columns:1fr;gap:20px;margin-top:32px}.toolbox-page{padding-top:40px}.tool-illustration{height:220px}.tool-tile-body{padding:24px}}
</style>
